on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
jobs:
  todo:
    runs-on: ubuntu-latest
    steps:
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v5.1.12
        with:
          INSERT_ISSUE_URLS: true