access_control:
  default_policy: deny
  rules:
    - domain: [auth.local.rachelf42.ca]
      policy: bypass
    - domain: ['*.admin.local.rachelf42.ca']
      policy: one_factor
      subject:
        - [group:admin]
    - domain: ['*.local.rachelf42.ca']
      policy: one_factor
      subject:
        - [group:all_users]
theme: dark
server:
  address: tcp://:9091/
log:
  level: info
  format: text
ntp:
  address: udp://time.cloudflare.com:123
authentication_backend:
  password_change:
    disable: true
  password_reset:
    disable: true
  ldap:
    implementation: custom
    address: ldap://lldap:3890
    user: cn=authelia,ou=people,dc=rachelf42,dc=ca
    timeout: 5s
    start_tls: false
    ### USERS DN
    base_dn: dc=rachelf42,dc=ca
    additional_users_dn: ou=people
    # allow signin with username OR email
    users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
    # allow signin with username ONLY
    # users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (&(member={dn})(objectclass=groupOfUniqueNames))
    attributes:
      group_name: cn
      username: uid
      mail: mail
      display_name: displayName
session:
  cookies:
    - domain: local.rachelf42.ca
      authelia_url: https://auth.local.rachelf42.ca
  redis:
    host: redis
    port: 6379
    timeout: 5s
    max_retries: 3
regulation:
  modes: [user]
  max_retries: 5
  find_time: 5m
  ban_time: 30m
storage:
  postgres:
    address: 'tcp://postgres:5432'
    database: 'authelia'
    schema: 'public'
    username: 'authelia'
    timeout: 5s
notifier:
  disable_startup_check: true
  filesystem:
    filename: /config/notification.txt
