access_control:
  default_policy: deny
  rules:
    ### BYPASS RULES
    # should be:
    # * as specific as possible, no wildcards
    # * commented with the reason for the bypass
    # * always kept on top
    - domain: # required self-bypass
        - auth.local.rachelf42.ca
        - auth.rachelf42.ca
      policy: bypass
    ### ADMIN SUBDOMAIN
    - domain: &admin
        - '*.admin.local.rachelf42.ca'
        - '*.admin.rachelf42.ca'
      policy: one_factor
      subject:
        - [group:admin]
    - domain:
        - lldap.local.rachelf42.ca
        - lldap.rachelf42.ca
      policy: one_factor
      subject:
        - [group:lldap_admin]
    - domain: *admin
      policy: deny
    ### CATCHALL - anything not listed above should be available to all users
    - domain: ['*.rachelf42.ca']
      policy: one_factor
      subject:
        - [group:all_users]
theme: dark
server:
  address: tcp://:9091/
log:
  level: info
  format: text
ntp:
  address: udp://time.cloudflare.com:123
authentication_backend:
  password_change:
    disable: true
  password_reset:
    disable: true
  ldap:
    implementation: lldap
    address: ldap://lldap:3890
    user: cn=authelia,ou=people,dc=rachelf42,dc=ca
    timeout: 30s
    start_tls: false
    base_dn: dc=rachelf42,dc=ca
session:
  cookies:
    - domain: local.rachelf42.ca
      authelia_url: https://auth.local.rachelf42.ca
  redis:
    host: redis
    port: 6379
    timeout: 5s
    max_retries: 3
regulation:
  modes: [user]
  max_retries: 5
  find_time: 5m
  ban_time: 30m
storage:
  postgres:
    address: 'tcp://postgres:5432'
    database: 'authelia'
    schema: 'public'
    username: 'authelia'
    timeout: 5s
notifier:
  disable_startup_check: true
  filesystem:
    filename: /config/notification.txt
