- homepage-refactorme-top:
    - Service-A-top:
        href: http://localhost
    - Service-B-top:
        href: http://localhost
- homepage-refactorme-left:
    - Service-A-left:
        href: http://localhost
    - Service-B-left:
        href: http://localhost
- homepage-refactorme-right:
    - Service-A-right:
        href: http://localhost
    - Service-B-right:
        href: http://localhost