# dclint disable require-project-name-field
# this file should only ever be extended, never run
services:
  base-nonet:
    restart: on-failure:5
    healthcheck:
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 300s
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    dns:
      - $DNS_HOST_ONE
      - $DNS_HOST_TWO
    security_opt:
      - no-new-privileges:true
    stop_grace_period: 1m30s
  base:
    extends:
      service: base-nonet
    networks:
      - main
  dozzle-agent:
    extends:
      service: base
    image: amir20/dozzle:v8.13.14@sha256:f16c49728f7c4ce94a56b1f92b1e0529d6d5c954397a64840426edaf0d5dea4e
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - '7007:7007'
    command: agent
    healthcheck: !reset {}