########## FRAGMENTS
x-defaults-nonet: &defaults-nonet
  extends:
    file: ./common.compose.yaml
    service: base-nonet
x-defaults: &defaults
  extends:
    file: ./common.compose.yaml
    service: base
########## STACK SETTINGS
name: control
networks:
  auth: {}
  main:
    name: main
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.69.0/24
########## SERVICES
services:
#################### MONITORS
  dozzle:
    extends:
      file: ./common.compose.yaml
      service: dozzle-agent
    depends_on: {traefik: {condition: service_started}}
    environment: {DOZZLE_REMOTE_AGENT: jenkins.local.rachelf42.ca:7007}
    ports: !reset []
    command: !reset null
    labels:
      traefik.enable: true
      traefik.http.routers.dozzle.tls: true
      traefik.http.routers.dozzle.tls.certresolver: cloudflare
      traefik.http.routers.dozzle.entrypoints: websecure
      traefik.http.routers.dozzle.rule: Host(`dozzle.admin.local.rachelf42.ca`)
      traefik.http.routers.dozzle.middlewares: authelia@file
      traefik.http.services.dozzle-control.loadbalancer.server.port: 8080
  # TODO: move all services below this point to nas
  # Issue URL: https://github.com/rachelf42/homelab/issues/61
  # and will need to reopen ports on control's containers
  # unless we do a tcp proxy thing
  # labels: waiting, hideFromCodeEditor
  kuma:
    <<: *defaults
    image: louislam/uptime-kuma:1.23.16@sha256:431fee3be822b04861cf0e35daf4beef6b7cb37391c5f26c3ad6e12ce280fe18
    depends_on:
      traefik: {condition: service_started}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $APPDIR/kuma:/app/data
    labels:
      traefik.enable: true
      traefik.http.routers.kuma.tls: true
      traefik.http.routers.kuma.tls.certresolver: cloudflare
      traefik.http.routers.kuma.entrypoints: websecure
      traefik.http.routers.kuma.rule: Host(`kuma.admin.local.rachelf42.ca`)
      traefik.http.routers.kuma.middlewares: authelia@file
  ddclient:
    <<: *defaults
    image: lscr.io/linuxserver/ddclient:4.0.0@sha256:f6318d23d903a0c38d1e25f3315af8c0d87b7a8ef9d52d3fe2688ee6a267cf6e
    volumes: [./config/ddclient.conf:/config/ddclient.conf]
    secrets: [cf-token]
    environment:
      PUID: $UID
      PGID: $GID
      TZ: $TZ
      FILE__CLOUDFLARE_TOKEN: /run/secrets/cf-token
    healthcheck: !reset {}
  myspeed:
    <<: *defaults
    image: germannewsmaker/myspeed:1.0.9@sha256:3a3e774b3f78d930a5a962d625b99bcb3d71730bfeb4a6b93e04fd38cfe7d9a9
    depends_on: {traefik: {condition: service_started}}
    volumes: [$APPDIR/myspeed:/myspeed/data]
    healthcheck: !reset {}
    labels:
      traefik.enable: true
      traefik.http.routers.myspeed.tls: true
      traefik.http.routers.myspeed.tls.certresolver: cloudflare
      traefik.http.routers.myspeed.entrypoints: websecure
      traefik.http.routers.myspeed.rule: Host(`myspeed.local.rachelf42.ca`)
      traefik.http.routers.myspeed.middlewares: authelia@file
#################### AUTHENTICATION
  postgres:
    <<: *defaults-nonet
    image: postgres:17.5@sha256:aadf2c0696f5ef357aa7a68da995137f0cf17bad0bf6e1f17de06ae5c769b302
    volumes:
      - $APPDIR/postgres:/var/lib/postgresql/data
      - ./config/psql-createdb.sh:/docker-entrypoint-initdb.d/psq-createdb.sh:ro
    secrets:
      - psql-root-password
      - psql-authelia-password
      - psql-lldap-password
    environment:
      POSTGRES_USER: rachel
      POSTGRES_PASSWORD_FILE: /run/secrets/psql-root-password
    ports: ['5432:5432']
    networks: [auth]
    healthcheck:
      test:
        - CMD-SHELL
        - PGPASSWORD=$$(cat $$POSTGRES_PASSWORD_FILE)
        - pg_isready
        - --username $${POSTGRES_USER}
        - --dbname $${POSTGRES_USER}
        - --no-password
    user: $UID:$GID
  lldap:
    <<: *defaults-nonet
    image: lldap/lldap:v0.6.2@sha256:9e605a66c02514bfcffd1b67cafb1e98d50992216bb2871d7ae44622047dd09d
    depends_on:
      traefik: {condition: service_started}
      postgres: {condition: service_healthy}
    volumes: [$APPDIR/lldap:/data]
    secrets:
      - lldap-psql-url
      - lldap-jwt
      - lldap-keyseed
      - lldap-adminpw
    environment:
      UID: $UID
      GID: $GID
      TZ: $TZ
      LLDAP_LDAP_BASE_DN: dc=rachelf42,dc=ca
      LLDAP_JWT_SECRET_FILE: /run/secrets/lldap-jwt
      LLDAP_KEY_SEED_FILE: /run/secrets/lldap-keyseed
      LLDAP_LDAP_USER_PASS_FILE: /run/secrets/lldap-adminpw
      LLDAP_DATABASE_URL_FILE: /run/secrets/lldap-psql-url
    ports: # open for terraform
      - '3890:3890'
      - '17170:17170'
    networks: [auth]
    labels:
      traefik.enable: true
      traefik.http.routers.lldap.tls: true
      traefik.http.routers.lldap.tls.certresolver: cloudflare
      traefik.http.routers.lldap.entrypoints: websecure
      traefik.http.routers.lldap.rule: Host(`lldap.admin.local.rachelf42.ca`)
      traefik.http.routers.lldap.middlewares: authelia@file
      traefik.http.services.lldap-control.loadbalancer.server.port: 17170
  redis:
    <<: *defaults-nonet
    image: bitnami/redis:8.2.1@sha256:25bf63f3caf75af4628c0dfcf39859ad1ac8abe135be85e99699f9637b16dc28
    volumes: [$APPDIR/redis:/bitnami]
    secrets: [redis-password]
    environment: {REDIS_PASSWORD_FILE: /run/secrets/redis-password}
    networks: [auth]
    healthcheck: !reset {}
    user: $UID:$GID
  authelia:
    <<: *defaults-nonet
    image: authelia/authelia:4.39.8@sha256:eb9c0ad2d029c483893f4a3c8bc1428577946796734d8441809aa609ab8abafe
    depends_on:
      postgres: {condition: service_healthy}
      lldap: {condition: service_healthy}
      redis: {condition: service_started}
      traefik: {condition: service_started}
    volumes:
      - $APPDIR/authelia:/config
      - ./config/authelia.yaml:/config/config.yaml:ro
      - ./config/authelia-acl.yaml:/config/access_control.yaml:ro
    secrets:
      - redis-password
      - psql-authelia-password
      - authelia-jwt
      - authelia-ldap-password
      - authelia-session-secret
      - authelia-storage-key
    environment:
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: /run/secrets/authelia-jwt
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: /run/secrets/authelia-ldap-password
      AUTHELIA_SESSION_SECRET_FILE: /run/secrets/authelia-session-secret
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/authelia-storage-key
      AUTHELIA_SESSION_REDIS_PASSWORD_FILE: /run/secrets/redis-password
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: /run/secrets/psql-authelia-password
    networks: [auth]
    command:
      - 'authelia'
      - '--config=/config/config.yaml'
      - '--config=/config/access_control.yaml'
    labels:
      traefik.enable: true
      traefik.http.routers.authelia.tls: true
      traefik.http.routers.authelia.tls.certresolver: cloudflare
      traefik.http.routers.authelia.entrypoints: websecure
      traefik.http.routers.authelia.rule: Host(`auth.local.rachelf42.ca`)
#################### FRONTEND
  traefik:
    # TODO: make traefik not dependent on proxmox
    # Issue URL: https://github.com/rachelf42/homelab/issues/83
    # probably move to nas
    # labels: waiting, hideFromCodeEditor
    <<: *defaults-nonet
    image: traefik:v3.4.4@sha256:9b0e9d788816d722703eae57ebf8b4d52ad98e02b76f0362d5a040ef46902ef7
    volumes:
      # for listening to container creation/deletion events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # static configuration file
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      # dynamic configuration files in this dir
      - ./config/traefik:/config:ro
      # certificate storage
      - $APPDIR/traefik/certs/acme.json:/acme.json
    secrets: [cf-token]
    environment: {CF_DNS_API_TOKEN_FILE: /run/secrets/cf-token}
    env_file: ./secrets/traefik-acme-email
    ports:
      - '80:80'
      - '81:8080'
      - '443:443'
    networks:
      auth: {}
      main: {ipv4_address: 192.168.69.69}
    healthcheck: !reset {}
    labels:
      traefik.enable: true
      traefik.http.routers.dashboard.tls: true
      traefik.http.routers.dashboard.tls.certresolver: cloudflare
      traefik.http.routers.dashboard.tls.domains[0].main: local.rachelf42.ca
      traefik.http.routers.dashboard.tls.domains[0].sans: '*.local.rachelf42.ca'
      traefik.http.routers.dashboard.entrypoints: websecure
      traefik.http.routers.dashboard.rule: Host(`traefik.local.rachelf42.ca`)
      traefik.http.routers.dashboard.service: api@internal
  homarr:
    <<: *defaults
    image: ghcr.io/homarr-labs/homarr:v1.34.0@sha256:ddd137a90782b7033ca5a94b110901ee107eff9bd438c5b6568c29ece18d37f7
    volumes: [$APPDIR/homarr:/appdata]
    env_file: ./secrets/homarr-key
    healthcheck: !reset {}
    labels:
      traefik.enable: true
      traefik.http.routers.homarr.tls: true
      traefik.http.routers.homarr.tls.certresolver: cloudflare
      traefik.http.routers.homarr.entrypoints: websecure
      traefik.http.routers.homarr.rule: Host(`local.rachelf42.ca`)
      traefik.http.routers.homarr.middlewares: authelia@file
      traefik.http.services.homarr-control.loadbalancer.server.port: 7575
########## HOUSEKEEPING
secrets:
  cf-token: {file: ./secrets/cf-token}
  psql-root-password: {file: ./secrets/psql-root-password}
  psql-authelia-password: {file: ./secrets/psql-authelia-password}
  psql-lldap-password: {file: ./secrets/psql-lldap-password}
  lldap-psql-url: {file: ./secrets/lldap-psql-url}
  lldap-jwt: {file: ./secrets/lldap-jwt}
  lldap-keyseed: {file: ./secrets/lldap-keyseed}
  lldap-adminpw: {file: ./secrets/lldap-adminpw}
  redis-password: {file: ./secrets/redis-password}
  authelia-ldap-password: {file: ./secrets/authelia-ldap-password}
  authelia-jwt: {file: ./secrets/authelia-jwt}
  authelia-session-secret: {file: ./secrets/authelia-session-secret}
  authelia-storage-key: {file: ./secrets/authelia-storage-key}