########## FRAGMENTS
x-defaults-nonet: &defaults-nonet
  extends:
    file: ./common.compose.yaml
    service: base-nonet
x-defaults: &defaults
  extends:
    file: ./common.compose.yaml
    service: base
########## STACK SETTINGS
name: control
networks:
  main:
    name: main
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.69.0/24
########## SERVICES
services:
#################### MONITORS
  dozzle:
    extends:
      file: ./common.compose.yaml
      service: dozzle-agent
    environment:
      DOZZLE_REMOTE_AGENT: jenkins.local.rachelf42.ca:7007
    ports: !override
      - '8080:8080'
    command: !reset null
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle-https.tls=true
      - traefik.http.routers.dozzle-https.tls.certresolver=cloudflare
      - traefik.http.routers.dozzle-https.tls.domains[0].main=local.rachelf42.ca
      - traefik.http.routers.dozzle-https.tls.domains[0].sans=*.local.rachelf42.ca
      - traefik.http.routers.dozzle-https.entrypoints=websecure
      - traefik.http.routers.dozzle-https.rule=Host(`dozzle.local.rachelf42.ca`)
  ddclient:
    <<: *defaults
    image: lscr.io/linuxserver/ddclient:4.0.0@sha256:ab657501e876361a84b488713f0332190fe5c2a9fe897a78452b2e98a8e6c97b
    volumes:
      - ./config/ddclient.conf:/config/ddclient.conf
    secrets:
      - cf-token
    environment:
      PUID: $UID
      PGID: $GID
      TZ: $TZ
      FILE__CLOUDFLARE_TOKEN: /run/secrets/cf-token
    healthcheck: !reset {}
  traefik:
    <<: *defaults-nonet
    image: traefik:v3.4.1@sha256:cd40ab7bc1f047731d5b22595203812343efcb6538014c4e93221cfc3a77217a
    volumes:
      # for listening to container creation/deletion events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # static configuration file
      - ./config/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      # dynamic configuration files in this dir
      - ./config/traefik/control:/config:ro
      # certificate storage
      - $APPDIR/traefik/certs/acme.json:/acme.json
    secrets:
      - cf-token
    environment:
      CF_DNS_API_TOKEN_FILE: /run/secrets/cf-token
    env_file:
      - ./secrets/traefik-acme-email
    ports:
      - '80:80'
      - '81:8080'
      - '443:443'
    networks:
      main:
        ipv4_address: 192.168.69.69
    healthcheck: !reset {}
########## HOUSEKEEPING
secrets:
  cf-token:
    file: ./secrets/cf-token