########## STACK SETTINGS
name: jenkins
networks:
  main:
########## SERVICES
services:
  dozzle:
    extends:
      file: ./common.compose.yaml
      service: dozzle-agent
  terraform:
    extends:
      file: ./common.compose.yaml
      service: base
    image: hashicorp/tfc-agent:1.22.5@sha256:965667704eab6bbd6cba6b6d5339b83ef8bb655bfc6774e3da2793639d6fbab7
    environment:
      TFC_AGENT_NAME: jenkins
      TFC_AGENT_AUTO_UPDATE: disabled # let renovate do it
      TFC_AGENT_SINGLE: true
    env_file: ./secrets/terraform_agent_token.env
    restart: always
    healthcheck: !reset {} # dont know why but dclint needs this not null
  webhookrelay:
    extends:
      file: ./common.compose.yaml
      service: base-nonet
    image: webhookrelay/webhookrelayd:1.34.4@sha256:5e947c3aa1d795437d9a108649bce66cba553eb444584e33bff5f28f2de28df1
    environment:
      BUCKETS: github-jenkins
    env_file: ./secrets/webhookrelay_agent_token.env
    network_mode: host
    healthcheck: !reset {}