########## STACK SETTINGS
name: media
networks:
  main:
########## SERVICES
services:
#################### MONITORS
  dozzle:
    extends:
      file: ./common.compose.yaml
      service: dozzle-agent
    environment:
      DOZZLE_REMOTE_AGENT: jenkins.local.rachelf42.ca:7007
    ports: !override
      - '8080:8080'
    command: !reset null
  ddclient:
    extends:
      file: ./common.compose.yaml
      service: base
    image: lscr.io/linuxserver/ddclient:4.0.0
    volumes:
      - ./config/ddclient.conf:/config/ddclient.conf
    secrets:
      - cf-token
    environment:
      PUID: $UID
      PGID: $GID
      TZ: $TZ
      FILE__CLOUDFLARE_TOKEN: /run/secrets/cf-token
    healthcheck: !reset {}
########## HOUSEKEEPING
secrets:
  cf-token:
    file: ./secrets/cf-token