########## STACK SETTINGS
name: media
########## SERVICES
services:
  dozzle:
    extends:
      file: ./common.compose.yaml
      service: base
    image: amir20/dozzle:v8.12.17@sha256:7a482fc570fa3a8cbc27afd4980e0a0c572e1489d954beb58758b1868fe4ac51
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - '8080:8080'
