########## STACK SETTINGS
name: media
########## SERVICES
services:
  dozzle:
    extends:
      file: ./common.compose.yaml
      service: base
    image: amir20/dozzle:v8.12.15@sha256:4d4d12db0575db8a5e80641f536ab0aa4ae81003d50aea5ea55fc80ae444ca66
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - '8080:8080'
