########## STACK SETTINGS
name: media
########## SERVICES
services:
  dozzle:
    extends:
      file: ./common.compose.yaml
      service: base
    image: amir20/dozzle:v8.12.18@sha256:0c21a86916ae55dd80a488d1125585709c9ac5a9c1807e684f22b2e1b057cd51
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - '8080:8080'
