########## STACK SETTINGS
name: media
########## SERVICES
services:
  dozzle:
    extends:
      file: ./common.compose.yaml
      service: dozzle-agent
    ports: !override
      - '8080:8080'
    command: !reset null
    environment:
      DOZZLE_REMOTE_AGENT: jenkins.local.rachelf42.ca:7007