- name: docker stacks
  hosts: [docker]
  become: true
  become_user: "{{ user_name }}" # override to root if escalation needed
  any_errors_fatal: true
  tasks:
    - name: start fresh
      become: true
      become_user: root
      when: "'jenk' not in group_names and start_fresh is defined and start_fresh | bool"
      block:
        - name: bring stack down
          async: 600
          poll: 10
          community.docker.docker_compose_v2:
            project_src: "{{ repodir }}/docker"
            check_files_existing: false # set via env var
            remove_orphans: true
            state: absent
            wait: true
        - name: nuke appdata
          ansible.builtin.file:
            path: /mount/nas/appdata
            state: absent
        - name: remake appdata
          ansible.builtin.file:
            path: /mount/nas/appdata
            state: directory
            owner: root
            group: root
            mode: "0777"
    - name: appdata requirements
      block:
        - name: redis dir
          when: inventory_hostname == "control"
          ansible.builtin.file:
            path: /mount/nas/appdata/redis
            owner: "{{ user_name}}"
            group: "{{ user_name}}"
            mode: "0777"
            state: directory
        - name: postgres dir
          when: inventory_hostname == "control"
          ansible.builtin.file:
            path: /mount/nas/appdata/postgres
            owner: "{{ user_name }}"
            group: "{{ user_name }}"
            mode: "0777"
            state: directory
        - name: traefik cert storage dir
          when: inventory_hostname == "control"
          ansible.builtin.file:
            path: /mount/nas/appdata/traefik/certs/
            owner: "{{ user_name }}"
            group: "{{ user_name }}"
            mode: "0777"
            state: directory
        - name: traefik cert storage exists
          when: inventory_hostname == "control"
          ansible.builtin.file:
            path: /mount/nas/appdata/traefik/certs/acme.json
            owner: "{{ user_name }}"
            group: "{{ user_name }}"
            mode: "0600"
            state: touch
            modification_time: preserve
            access_time: preserve
    - name: repo dest exists
      become: true
      become_user: root
      ansible.builtin.file:
        path: "{{ repodir }}"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: "0777"
    - name: acl set
      become: true
      become_user: root
      ansible.posix.acl:
        path: "{{ repodir }}"
        entity: docker
        etype: group
        permissions: rwX # capital X means execute allowed IF normal x bit set OR if is directory
        default: true
        recursive: true
        state: present
    - name: update repo
      ansible.builtin.git:
        repo: git@github.com:{{ account_name }}/homelab.git
        dest: "{{ repodir }}"
        # TODO: ensure this never changes on the main branch
        # Issue URL: https://github.com/rachelf42/homelab/issues/15
        version: authelia
        # we can set it to whatever our current branch is when we're working on stuff, but
        # if someone pulls from main they should always get "version: main"
        force: true
        accept_newhostkey: true
        clone: true
        update: true
    - name: tempdir
      register: tempdir
      ansible.builtin.tempfile:
        state: directory
    - name: ssh key
      ansible.builtin.copy:
        src: jenkins_ssh_key
        dest: "{{ tempdir.path }}/key"
        mode: "0600"
    - name: pull secrets # noqa command-instead-of-shell
      changed_when: true
      ansible.builtin.shell:
        cmd: SYNC_KEY={{ tempdir.path }}/key SYNC_USER=rachel ./scripts/pullSecrets.sh
        chdir: "{{ repodir }}"
    - name: delete tempdir
      ansible.builtin.file:
        path: "{{ tempdir.path }}"
        state: absent
    - name: pull images
      async: 600
      poll: 10
      retries: 3
      community.docker.docker_compose_v2_pull:
        project_src: "{{ repodir }}/docker"
        check_files_existing: false # set via env var
        policy: always
    - name: bring stack up
      async: 600
      poll: 10
      community.docker.docker_compose_v2:
        project_src: "{{ repodir }}/docker"
        check_files_existing: false # set via env var
        pull: never # because pull is a seperate task
        remove_orphans: true
        state: present
        wait: true