- name: docker stacks
  hosts: [docker]
  become: true
  become_user: "{{ user_name }}"
  any_errors_fatal: true
  tasks:
    - name: repo dest exists
      become: true
      become_user: root
      ansible.builtin.file:
        path: "{{ repodir }}"
        state: directory
        owner: "{{ user_name }}"
        group: docker
        mode: "0777"
    - name: update repo
      ansible.builtin.git:
        repo: git@github.com:{{ account_name }}/homelab.git
        dest: "{{ repodir }}"
        # TODO: ensure this never changes on the main branch
        # Issue URL: https://github.com/rachelf42/homelab/issues/15
        version: main
        # we can set it to whatever our current branch is when we're working on stuff, but
        # if someone pulls from main they should always get "version: main"
        force: true
        accept_newhostkey: true
        clone: true
        update: true
    - name: tempdir
      register: tempdir
      ansible.builtin.tempfile:
        state: directory
    - name: ssh key
      ansible.builtin.copy:
        src: jenkins_ssh_key
        dest: "{{ tempdir.path }}/key"
        mode: "0600"
    - name: pull secrets # noqa command-instead-of-shell
      changed_when: true
      ansible.builtin.shell:
        cmd: SYNC_KEY={{ tempdir.path }}/key SYNC_USER=rachel ./scripts/pullSecrets.sh
        chdir: /homelab
    - name: delete tempdir
      ansible.builtin.file:
        path: "{{ tempdir.path }}"
        state: absent
    - name: pull images
      async: 600
      poll: 10
      retries: 3
      community.docker.docker_compose_v2_pull:
        project_src: "{{ repodir }}/docker"
        files: "{{ inventory_hostname }}.compose.yaml"
        policy: always
    - name: bring stack up
      async: 600
      poll: 10
      community.docker.docker_compose_v2:
        project_src: "{{ repodir }}/docker"
        files: "{{ inventory_hostname }}.compose.yaml"
        pull: never # because pull is a seperate task
        remove_orphans: true
        state: present
        wait: true