# Adapted from: https://github.com/ChristianLempa/boilerplates/blob/main/ansible/ubuntu/
# specifically maint-*.yaml
- name: waiting on SSH
  gather_facts: false
  hosts: all
  any_errors_fatal: true
  tasks:
    - ansible.builtin.wait_for_connection:
        timeout: 3600
        sleep: 10
- name: check disk space
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: check disk space
      become: true
      ansible.builtin.shell:
        cmd: |
          set -o pipefail -o nounset -o errexit
          df --portability --human-readable / | awk 'NR==2 {print $5}'
        executable: /bin/bash
      changed_when: false
      check_mode: false
      register: disk_usage
    - ansible.builtin.debug:
        msg: Main filesystem disk usage is at {{ disk_usage.stdout[:-1] }} percent
    - name: send notification
      when: disk_usage.stdout[:-1] | int > 80
      delegate_to: localhost
      community.general.pushover:
        msg: "{{ inventory_hostname }}'s main disk is at {{ disk_usage.stdout }}!"
        user_key: "{{ pushover_user_key }}"
        app_token: "{{ pushover_api_key }}"
        device: "{{ pushover_devices }}"
        pri: 1
- name: check if jenkins has an update
  hosts: jenkcontroller
  any_errors_fatal: true
  tasks:
    - name: apt update
      changed_when: false
      become: true
      async: 600
      poll: 10
      retries: 10
      ansible.builtin.apt:
        update_cache: true
    - name: fail here means there is no update
      become: true
      register: checkjenk
      changed_when: false
      ignore_errors: true    # module doesnt provide the fact i need
      ansible.builtin.shell: # noqa: command-instead-of-module
        cmd: apt-get -u upgrade --assume-no | grep jenkins
    - name: set fact
      when: checkjenk.rc == 0
      ansible.builtin.set_fact:
        jenkupdate: true
    - name: send notif
      when: jenkupdate is defined
      delegate_to: localhost
      community.general.pushover:
        msg: Jenkins has updated! Update the controller manually!
        user_key: "{{ pushover_user_key }}"
        app_token: "{{ pushover_api_key }}"
        device: "{{ pushover_devices }}"
- name: package manager upgrades
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: apt
      become: true
      when: false # ('ubuntu' or 'debian' in group_names) and jenkupdate is not defined
      async: 600
      poll: 10
      retries: 10
      ansible.builtin.apt:
        update_cache: true
        upgrade: safe
        autoremove: true
        autoclean: true
    - name: pipx - root
      when: "'devmachine' in group_names or 'jenkins' in group_names"
      become: true
      async: 600
      poll: 10
      retries: 10
      changed_when: true
      ansible.builtin.command: pipx upgrade-all
    - name: pipx - nonroot
      when: "'devmachine' in group_names or 'jenkins' in group_names"
      async: 600
      poll: 10
      retries: 10
      changed_when: true
      ansible.builtin.command: pipx upgrade-all
    - name: pipx - jenkins
      become: true
      become_user: jenkins
      when: "'jenkcontroller' in group_names"
      async: 600
      poll: 10
      retries: 10
      changed_when: true
      ansible.builtin.command: pipx upgrade-all
- name: check if system reboot is required
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: check if system reboot is required
      become: true
      ansible.builtin.stat:
        path: /run/reboot-required
      register: reboot_required
    - name: send notification
      when: reboot_required.stat.exists
      delegate_to: localhost
      community.general.pushover:
        msg: "{{ inventory_hostname }} is reporting a reboot is required!"
        user_key: "{{ pushover_user_key }}"
        app_token: "{{ pushover_api_key }}"
        device: "{{ pushover_devices }}"
