jenkins:
  systemMessage: |
    Jenkins configured automatically by Jenkins Configuration as Code plugin.
    Please do not change any settings manually.
  numExecutors: 2
  scmCheckoutRetryCount: 2
  mode: NORMAL
  globalNodeProperties:
    - envVars:
        env:
          - key: PACKER_NO_COLOR
            value: true
          - key: TF_IN_AUTOMATION
            value: jenkins
          - key: TF_INPUT
            value: false
          - key: TF_CLI_ARGS
            value: -no-color
          - key: ANSIBLE_NOCOWS
            value: 1
          - key: ANSIBLE_STDOUT_CALLBACK
            value: ansible.builtin.default
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: meta
          name: Jenkins Controlling Jenkins
          password: ${readFile:/var/lib/jenkins/userContent/meta-login}
        - id: rachel
          name: Rachel Falder
          password: ${json:password:${readFile:/var/lib/jenkins/userContent/secrets.json}}
          properties:
            - consoleUrlProvider
            - myView
            - preferredProvider:
                providerId: default
            - theme:
                theme: dark
            - timezone
            - experimentalFlags
            - mailer:
                emailAddress: ${json:email:${readFile:/var/lib/jenkins/userContent/secrets.json}}
            - apiToken
tool:
  git:
    installations:
      - home: git
        name: Default
unclassified:
  location:
    adminAddress: address not configured yet <nobody@nowhere>
    url: http://jenkins.local.rachelf42.ca:8080/
  mailer:
    replyToAddress: do-not-reply@acme.org
    smtpHost: smtp.acme.org
    smtpPort: 4441
jobs:
  - providedEnv:
      GITHUB_WEBHOOK_TOKEN: ${readFile:/var/lib/jenkins/userContent/gh-wh-token}
  - url: https://raw.githubusercontent.com/rachelf42/homelab/refs/heads/main/jenkins/jobs/main.groovy
  - url: https://raw.githubusercontent.com/rachelf42/homelab/refs/heads/main/jenkins/jobs/daily.groovy
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: meta-login
              description: Password to log into Jenkins from within a Jenkinsfile
              scope: GLOBAL
              username: meta
              password: ${readFile:/var/lib/jenkins/userContent/meta-login}
              usernameSecret: false
          - basicSSHUserPrivateKey:
              id: homelab-pull-secrets
              description: SSH key to pull secret files used via symlink into the workspace
              scope: GLOBAL
              username: rachel
              privateKeySource:
                directEntry:
                  privateKey: ${readFile:/var/lib/jenkins/userContent/ssh_key}
          - string:
              id: terratoken
              description: HCP Terraform Token
              scope: GLOBAL
              secret: ${readFile:/var/lib/jenkins/userContent/terratoken}
          - string:
              id: ansivault
              description: Ansible Vault Password
              scope: GLOBAL
              secret: ${json:password:${readFile:/var/lib/jenkins/userContent/secrets.json}}
          - string:
              id: pushovertoken
              description: App Token for Pushover.net notifications
              scope: GLOBAL
              secret: ${readFile:/var/lib/jenkins/userContent/pushovertoken}
          - string:
              id: pushoverkey
              description: User Key for Pushover.net notifications
              scope: GLOBAL
              secret: ${readFile:/var/lib/jenkins/userContent/pushoverkey}
