jenkins:
  systemMessage: |
    Jenkins configured automatically by Jenkins Configuration as Code plugin.
    Please do not change any settings manually.
  numExecutors: 5
  scmCheckoutRetryCount: 2
  mode: NORMAL
  globalNodeProperties:
    - envVars:
        env:
          - key: FOO
            value: BAR
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: "rachel"
          name: "Rachel Falder"
          password: ${json:password:${readFile:/var/lib/jenkins/userContent/secrets.json}}
          properties:
            - "consoleUrlProvider"
            - "myView"
            - preferredProvider:
                providerId: "default"
            - theme:
                theme: "dark"
            - "timezone"
            - "experimentalFlags"
            - mailer:
                emailAddress: ${json:email:${readFile:/var/lib/jenkins/userContent/secrets.json}}
            - "apiToken"
tool:
  git:
    installations:
      - home: git
        name: Default
unclassified:
  location:
    adminAddress: address not configured yet <nobody@nowhere>
    url: http://jenkins.local.rachelf42.ca:8080/
  mailer:
    replyToAddress: do-not-reply@acme.org
    smtpHost: smtp.acme.org
    smtpPort: 4441
jobs:
  - url: https://raw.githubusercontent.com/rachelf42/homelab/refs/heads/main/jenkins/jobs/main.groovy
credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              id: homelab-pull-secrets
              scope: GLOBAL
              username: rachel
              privateKeySource:
                directEntry:
                  privateKey: "${readFile:/var/lib/jenkins/userContent/ssh_key}"
          - string:
              id: terratoken
              description: HCP Terraform Token
              scope: GLOBAL
              secret: "${readFile:/var/lib/jenkins/userContent/terratoken}"