on: # yamllint disable-line rule:truthy
  push:
    branches: [main, renovate/*]
  pull_request:
    branches: [main]
jobs:
  lint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run ShellCheck
        uses: Azbagheri/shell-linter@30a9cf3f6cf25c08fc98f10d7dc4167f7b5c0c00 # v0.8.0
        with:
          path: "scripts"

      - name: Install YAMLlint
        run: pip install yamllint
      - name: Fake Ansible Vault
        run: mv ansible/civault.yaml secrets/ansible_vault.yaml
      - name: Run YAMLlint
        run: yamllint .

      - name: Setup HashiCorp Packer
        uses: hashicorp/setup-packer@1aa358be5cf73883762b302a3a03abd66e75b232 # v3.1.0
      - name: Fake Proxmox Secret
        run: |
          echo 'proxmox_api_token_secret = "this-is-totally-a-legit-secret"' > packer/secret.auto.pkrvars.hcl
      - name: Placeholder SSH Key
        run: ssh-keygen -f ansible_ssh_key
      - name: Initialize Packer
        run: packer init packer
      - name: Run Packer Validate
        run: packer validate packer

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: "1.12.1" # TODO: make sure this changes with the .tf files
                                      # labels: bug
                                      # Issue URL: https://github.com/rachelf42/homelab/issues/32
      - name: Initialize Terraform
        run: terraform -chdir=terraform init -cloud=false
      - name: Run Terraform Validate
        run: terraform -chdir=terraform validate

      - name: Run Ansible-Lint
        uses: ansible/ansible-lint@e98f9b38769d45cbe3c55a23b2eb25631babe7c4 # v25.4.0
        env:
          ANSIBLE_VAULT_PASS: SuperSecureSecretPassword
        with:
          gh_action_ref: v25.4.0
          working_directory: ansible
          requirements_file: requirements.yaml

      - name: Run Docker-Compose-Lint
        run: npx dclint docker/*.compose.yaml --max-warnings 0
  deploy:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: lint
    if: github.event_name == push
    steps:
      - name: hellodeploy
        run: echo HELLO FROM DEPLOY JOB