name: Auto Approved
on: # yamllint disable-line rule:truthy
  pull_request_target:
  pull_request_review:
  pull_request:
    types: [ready_for_review]
jobs:
  autoapprove:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'rachelf42' && github.event.pull_request.draft == false
    steps:
      - uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363 # v4.0.0
        with:
          github-token: ${{ secrets.BOT_PAT }}
  automerge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: reitermarkus/automerge@634d0a4b51134c163eee182ac9aa79133eb33e8d # v2.8.0
        with:
          token: ${{ secrets.BOT_PAT }}
          merge-method: squash